"""Add PO lifecycle fields

Revision ID: 4c4cc8a4c3da
Revises: 0a7d230093c2
Create Date: 2026-07-08 11:34:28.011449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c4cc8a4c3da'
down_revision: Union[str, Sequence[str], None] = '0a7d230093c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_orders', sa.Column('created_by_id', sa.String(), nullable=True))
    op.add_column('purchase_orders', sa.Column('sent_by_id', sa.String(), nullable=True))
    op.add_column('purchase_orders', sa.Column('cancelled_reason', sa.String(), nullable=True))
    op.create_foreign_key('fk_po_sent_by', 'purchase_orders', 'users', ['sent_by_id'], ['id'])
    op.create_foreign_key('fk_po_created_by', 'purchase_orders', 'users', ['created_by_id'], ['id'])
    
    # Add Cancelled to enum
    op.execute("ALTER TYPE postatusenum ADD VALUE IF NOT EXISTS 'Cancelled'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_po_created_by', 'purchase_orders', type_='foreignkey')
    op.drop_constraint('fk_po_sent_by', 'purchase_orders', type_='foreignkey')
    op.drop_column('purchase_orders', 'cancelled_reason')
    op.drop_column('purchase_orders', 'sent_by_id')
    op.drop_column('purchase_orders', 'created_by_id')
    # ### end Alembic commands ###
