"""Add modifiers and routing

Revision ID: a5a9d0f871ae
Revises: 2249f2573076
Create Date: 2026-07-01 11:54:40.509531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5a9d0f871ae'
down_revision: Union[str, Sequence[str], None] = '2249f2573076'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_modifier_groups',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('menu_item_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.Column('min_selections', sa.Integer(), nullable=True),
    sa.Column('max_selections', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_modifiers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('group_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price_adjustment', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['item_modifier_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction_item_modifiers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('transaction_item_id', sa.String(), nullable=False),
    sa.Column('modifier_id', sa.String(), nullable=False),
    sa.Column('price_at_time', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['modifier_id'], ['item_modifiers.id'], ),
    sa.ForeignKeyConstraint(['transaction_item_id'], ['transaction_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    order_type_enum = sa.Enum('Dine-In', 'Takeaway', name='ordertypeenum')
    order_type_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('transactions', sa.Column('order_type', order_type_enum, nullable=False, server_default='Takeaway'))
    op.add_column('transactions', sa.Column('routing_number', sa.String(), nullable=True))
    op.add_column('users', sa.Column('hashed_pin', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hashed_pin')
    op.drop_column('transactions', 'routing_number')
    op.drop_column('transactions', 'order_type')
    order_type_enum = sa.Enum('Dine-In', 'Takeaway', name='ordertypeenum')
    order_type_enum.drop(op.get_bind(), checkfirst=True)
    op.drop_table('transaction_item_modifiers')
    op.drop_table('item_modifiers')
    op.drop_table('item_modifier_groups')
    # ### end Alembic commands ###
