"""migrate_floats_to_numeric

Revision ID: a5d4310456d7
Revises: b0bf78816094
Create Date: 2026-07-12 09:07:44.848241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5d4310456d7'
down_revision: Union[str, Sequence[str], None] = 'b0bf78816094'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ingredients', 'stock_level',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=3),
               existing_nullable=True,
               postgresql_using='stock_level::numeric(10,3)')
    op.alter_column('ingredients', 'reorder_point',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=3),
               existing_nullable=True,
               postgresql_using='reorder_point::numeric(10,3)')
    op.alter_column('ingredients', 'unit_cost',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True,
               postgresql_using='unit_cost::numeric(10,2)')
    op.alter_column('modifier_recipes', 'quantity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=3),
               existing_nullable=False,
               postgresql_using='quantity::numeric(10,3)')
    op.alter_column('purchase_orders', 'current_stock',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=3),
               existing_nullable=False,
               postgresql_using='current_stock::numeric(10,3)')
    op.alter_column('purchase_orders', 'reorder_point',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=3),
               existing_nullable=False,
               postgresql_using='reorder_point::numeric(10,3)')
    op.alter_column('purchase_orders', 'suggested_quantity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=3),
               existing_nullable=False,
               postgresql_using='suggested_quantity::numeric(10,3)')
    op.alter_column('purchase_orders', 'actual_received_quantity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=3),
               existing_nullable=True,
               postgresql_using='actual_received_quantity::numeric(10,3)')
    op.alter_column('recipes', 'quantity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=3),
               existing_nullable=False,
               postgresql_using='quantity::numeric(10,3)')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recipes', 'quantity',
               existing_type=sa.Numeric(precision=10, scale=3),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('purchase_orders', 'actual_received_quantity',
               existing_type=sa.Numeric(precision=10, scale=3),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('purchase_orders', 'suggested_quantity',
               existing_type=sa.Numeric(precision=10, scale=3),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('purchase_orders', 'reorder_point',
               existing_type=sa.Numeric(precision=10, scale=3),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('purchase_orders', 'current_stock',
               existing_type=sa.Numeric(precision=10, scale=3),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('modifier_recipes', 'quantity',
               existing_type=sa.Numeric(precision=10, scale=3),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('ingredients', 'unit_cost',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('ingredients', 'reorder_point',
               existing_type=sa.Numeric(precision=10, scale=3),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('ingredients', 'stock_level',
               existing_type=sa.Numeric(precision=10, scale=3),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    # ### end Alembic commands ###
