"""Add actual_received_quantity and new PO statuses

Revision ID: b0bf78816094
Revises: 4c4cc8a4c3da
Create Date: 2026-07-11 22:14:45.009060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0bf78816094'
down_revision: Union[str, Sequence[str], None] = '4c4cc8a4c3da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_orders', sa.Column('actual_received_quantity', sa.Float(), nullable=True))
    op.execute("ALTER TYPE postatusenum ADD VALUE IF NOT EXISTS 'Partially Received'")
    op.execute("ALTER TYPE postatusenum ADD VALUE IF NOT EXISTS 'Over-Received'")
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_orders', 'actual_received_quantity')
    # ### end Alembic commands ###
