"""Add is_active and other updates

Revision ID: b5ca80b62b71
Revises: 304201000797
Create Date: 2026-06-28 11:57:34.416410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5ca80b62b71'
down_revision: Union[str, Sequence[str], None] = '304201000797'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suppliers', sa.Column('contact_person', sa.String(), nullable=True))
    op.add_column('suppliers', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    op.drop_column('suppliers', 'is_active')
    op.drop_column('suppliers', 'contact_person')
    # ### end Alembic commands ###
