"""add tax and subtotal to transactions

Revision ID: d513e210fda2
Revises: fe8464666284
Create Date: 2026-07-02 16:46:51.597009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd513e210fda2'
down_revision: Union[str, Sequence[str], None] = 'fe8464666284'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('subtotal', sa.Float(), nullable=False, server_default="0.0"))
    op.add_column('transactions', sa.Column('tax', sa.Float(), nullable=False, server_default="0.0"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'tax')
    op.drop_column('transactions', 'subtotal')
    # ### end Alembic commands ###
