"""Add real COGS and modifier recipes

Revision ID: fe8464666284
Revises: a5a9d0f871c0
Create Date: 2026-07-02 00:09:17.452474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe8464666284'
down_revision: Union[str, Sequence[str], None] = 'a5a9d0f871c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modifier_recipes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('modifier_id', sa.String(), nullable=True),
    sa.Column('ingredient_id', sa.String(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ),
    sa.ForeignKeyConstraint(['modifier_id'], ['item_modifiers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('ingredients', sa.Column('unit_cost', sa.Float(), nullable=True))
    op.add_column('transaction_item_modifiers', sa.Column('cogs_per_unit', sa.Float(), server_default='0.0', nullable=False))
    op.add_column('transaction_items', sa.Column('cogs_per_unit', sa.Float(), server_default='0.0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction_items', 'cogs_per_unit')
    op.drop_column('transaction_item_modifiers', 'cogs_per_unit')
    op.drop_column('ingredients', 'unit_cost')
    op.drop_table('modifier_recipes')
    # ### end Alembic commands ###
